import = ["/home/kristian/.dotfiles/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
